# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mc-settings}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Edwin Cruz", "Colin Shield"]
  s.date = %q{2011-09-06}
  s.description = %q{implement custom keys indenendently of environment}
  s.email = %q{rubydev@modcloth.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/mc-settings.rb",
    "lib/setting.rb",
    "mc-settings.gemspec",
    "spec/fixtures/joes-colors.yml",
    "spec/fixtures/sample.yml",
    "spec/fixtures/shipping.yml",
    "spec/mc_settings_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/settings_helper.rb"
  ]
  s.homepage = %q{http://github.com/modcloth/mc-settings}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.summary = %q{Manage settings per environment}
  s.test_files = [
    "spec/mc_settings_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/settings_helper.rb"
  ]

  s.add_development_dependency "rspec"
  s.add_development_dependency "jeweler"
  s.add_development_dependency "rdoc"
end

